/* eslint-disable */
const { mkdirSync, readFileSync, writeFileSync } = require('fs');
const { sync } = require('glob');
const { basename, dirname, extname, join } = require('path');

const translationsPath = join(__dirname, '../i18n/**/*.json');
const outputPath = join(__dirname, '../generated/i18n.generated.ts');

function generate() {
  const files = sync(translationsPath);
  const translations = {};

  for (const file of files) {
    const namespace = basename(file, extname(file)); // e.g. validation.json → "validation"
    const json = JSON.parse(readFileSync(file, 'utf8'));
    translations[namespace] = json;
  }

  const typeDef = buildRootType('I18nTranslations', translations);

  const header = `/* DO NOT EDIT, file generated by custom generator */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
`;

  const footer = `/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
`;

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, header + typeDef + '\n' + footer, 'utf8');
  console.log(`✅ Generated: ${outputPath}`);
}

// build the root `export type I18nTranslations = { ... }`
function buildRootType(name, obj, indent = 0) {
  const spaces = '  '.repeat(indent);
  let output = `${spaces}export type ${name} = {\n`;

  for (const key of Object.keys(obj)) {
    output += `${spaces}  "${key}": ${buildNestedType(obj[key], indent + 1)};\n`;
  }

  output += `${spaces}}`;
  return output;
}

// build nested `{ ... }` structures (no `export`)
function buildNestedType(obj, indent) {
  const spaces = '  '.repeat(indent);
  let output = `{\n`;

  for (const key of Object.keys(obj)) {
    if (typeof obj[key] === 'object' && obj[key] !== null) {
      output += `${spaces}  "${key}": ${buildNestedType(obj[key], indent + 1)};\n`;
    } else {
      output += `${spaces}  "${key}": string;\n`;
    }
  }

  output += `${spaces}}`;
  return output;
}

generate();
